### ISSUE TITLE
label of circular range fan is not updated if radius is modified by dragging the handle on the circle

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODINv2#36]
The circular range fan updates the label correctly if one uses the properties field but it gets out of sync if the user drags the handle on the ring using the mouse. The property value changes correctly.

<img width="580" alt="image" src="https://github.com/syncpoint/ODINv2/assets/38359572/3fec37e8-3760-4d59-90ae-f294e2bd4db0">

**Comment by dehmer** [comment]
fixed.
