### ISSUE TITLE
Import/Export buttons disabled for some reason.

### ISSUE THREAD

**Issue by RT109A1** [syncpoint/ODINv2#58]
Exactly what it says on the box. No idea why is this happening.
![image](https://github.com/user-attachments/assets/f9498c44-24a5-4e67-82bf-d537c6cebc93)

**Comment by dehmer** [comment]
Sorry, but this feature was not implemented. It's just a dummy for future additions.

There are two ways to to import data though:
* Dragging a GeoJSON file onto the map
* Pasting our own clipboard test format

For the second option, you would probably want to experiment copying/pasting layer/feature selections inside the application and inspect the text in clipboard.
